/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Global;

import Global.ImageStruct;
import java.awt.Color;
import java.awt.Graphics;
/**
 *
 * @author demin
 */
public class JPanel2 extends javax.swing.JPanel{

    /**
     * Creates new form JPanel2
     */
    private ImageStruct point;
    private int width;
    private int height;
    
    public JPanel2() {
        initComponents();
    }
    
    public void paintMoldebroh(ImageStruct image,int width, int height, Graphics g){
        this.point=image;
        repaint();
        g.setColor(Color.WHITE);
        g.fillRect(0,0,this.getWidth(),this.getHeight());
        for (int y=0; y<height;y++){
            for (int x=0; x<width;x++){
                int colors=point.pixels[x][y].red;
                g.setColor(new Color(colors,colors,colors));
                g.drawLine(x, y, x, y);
            }
        }
        this.paint(g);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
